# Generated by Django 4.2.6 on 2023-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('cat', models.IntegerField()),
                ('pdetail', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
