# Generated by Django 4.2.6 on 2023-11-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.IntegerField(verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdetail',
            field=models.CharField(max_length=300, verbose_name='Product Name'),
        ),
    ]
