# Generated by Django 4.2.6 on 2023-11-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0002_alter_products_cat_alter_products_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Shoes'), (2, 'Sandals'), (3, 'Flip Flops'), (4, 'Crocs')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdetail',
            field=models.CharField(max_length=300, verbose_name='Product Detail'),
        ),
    ]
