# Generated by Django 4.2.6 on 2023-11-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0006_alter_cart_pid_alter_cart_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
