# Generated by Django 4.2.6 on 2023-11-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
