# Generated by Django 4.2.6 on 2023-11-02 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0011_makepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='product',
            field=models.ForeignKey(db_column='oid', on_delete=django.db.models.deletion.CASCADE, to='footapp.products'),
        ),
    ]
