# Generated by Django 4.2.6 on 2023-11-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0012_alter_makepayment_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makepayment',
            old_name='product',
            new_name='pid',
        ),
    ]
